### ISSUE TITLE
Error: Account id of stack environment must be a 'string' but received 'number'

### ISSUE THREAD

**Issue by nitindr-onetrust** [aws-samples/amazon-mwaa-examples#54] opened 2023-08-28 08:29 UTC
I'm getting the following error while trying to deploy the  "start-stop-mwaa-environment" stack in cdk using "npm run deploy" command

```
Error: Account id of stack environment must be a 'string' but received 'number'
    at MwaaMainStack.parseEnvironment (/home/nitin/amazon-mwaa-examples/usecases/start-stop-mwaa-environment/node_modules/aws-cdk-lib/core/lib/stack.js:1:18573)
    at new Stack (/home/nitin/amazon-mwaa-examples/usecases/start-stop-mwaa-environment/node_modules/aws-cdk-lib/core/lib/stack.js:1:2885)
    at new MwaaMainStack (/home/nitin/amazon-mwaa-examples/usecases/start-stop-mwaa-environment/lib/infrastructure/mwaa-main-stack.ts:58:5)
    at Object.<anonymous> (/home/nitin/amazon-mwaa-examples/usecases/start-stop-mwaa-environment/bin/mwaa-pause-resume.ts:29:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module.m._compile (/home/nitin/amazon-mwaa-examples/usecases/start-stop-mwaa-environment/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Object.require.extensions.<computed> [as .ts] (/home/nitin/amazon-mwaa-examples/usecases/start-stop-mwaa-environment/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
```
Any help would be appreciated

**Comment by crupakheti** [comment] 2023-08-31 13:37
Hey @nitindr-onetrust, thanks for brining this issue to our attention. We have identified the cause and are working on a fix. In the interim could you put your account number inside a quote in the `.env` file and report back if that resolves your issue? Thanks!

**Comment by JuanIgnacioHernandez** [comment] 2023-09-01 21:17
Hi @crupakheti , just wanted to say that i downgraded MWAA enviroment version to 2.5.1, but im still having the same issue as @nitindr-onetrust .

The commands `npm i` and `npm run build` executes without errors.
The command `npm test` fails some tests and all errors are the same:

"_Cannot retrieve value from context provider vpc-provider since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack._"

And both the command `cdk boostrap` and `npm run deploy` gives me the error of this issue:

"_Account id of stack environment must be a 'string' but received 'number'_" error.

I have my `.env` file properly configured and i already tried putting account number inside quotes but does not work for me.

Please tell me what other information I can provide so that you can help me. Thank you so much!

**Comment by nitindr-onetrust** [comment] 2023-09-05 13:23
Hi @JuanIgnacioHernandez 

Can you try to include the Account_ID in quotes while exporting the CDK_DEFAULT_ACCOUNT 
ex: ```
export CDK_DEFAULT_ACCOUNT="123456789"

export CDK_DEFAULT_REGION="us-east-1"
```

**Comment by crupakheti** [comment] 2023-09-05 17:51
Hey @JuanIgnacioHernandez, I am glad that you identified the right place to edit the code to avoid string to number conversion for the account id. We are working on a similar solution. We will close this issue when the solution is merged. Thank you!

**Comment by crupakheti** [comment] 2024-04-12 13:52
Closing as the issue has been fixed in a previous PR.

**Closed by crupakheti** 2024-04-12 13:52 UTC
